services:
  - type: web
    name: gigshield-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn src.app_server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  - type: worker
    name: gigshield-pipeline
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run_pipeline.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
